### ISSUE TITLE
E-mail function

### ISSUE THREAD

**Issue by meelih** [raghavendar-ts/ElasticTab-Elasticsearch-to-Excel-Report#4]
I've been trying to e-mail reports with the following properties;

`mail.smtp.port=587`
`mail.smtp.auth=true`
`mail.smtp.starttls.enable=true`
`mail.smtp.host=smtp.gmail.com`
`username=elastictab12@gmail.com`
`password=blahblahblah`

I turned on "less secure apps" option for that google account, but i couldn't send an e-mail until yet. Btw using with ES 2.2.1. What am i missing ?

**Comment by raghavendar-ts** [comment]
Hi. Can you post the error statements which you get in the command console when you hit the E-Mail button? By the way, Elasticsearch version should not be a concern for this E-Mail issue.

**Comment by meelih** [comment]
Sure. I hope that will do. By the way i fixed the "unknown host" errors, so you can ignore them.
[elastictab_log.txt](https://github.com/raghavendar-ts/ElasticTab-Elasticsearch-to-Excel-Report/files/209857/elastictab_log.txt)

**Comment by raghavendar-ts** [comment]
I don't see any issues from my side. Does the problem still exist?
